version: "3.7"

# First server setup
redis:
    build: redis
    expose:
        - "6379"

api:
    build: api
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_ID=0
        - INPUT_QUEUE=input_queue
    volumes:
        - api:/api
    expose:
        - "5000"
    links:
        - redis1
ml_service:
    build: ml_service
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_ID=0
        - INPUT_QUEUE=input_queue

# Load balancer
nginx:
    build: nginx
    ports:
        - "127.0.0.1:5000:80"
