# First server setup
redis1:
    build: redis
api1:
    build: api
    environment:
        - REDIS_HOST=redis1
    volumes:
        - api:/api
    links:
        - redis1

# Second server setup
redis2:
    build: redis
api2:
    build: api
    environment:
        - REDIS_HOST=redis2
    volumes:
        - api:/api
    links:
        - redis2

# Load balancer
nginx:
    build: nginx
    ports:
        - "5000:80"
    links:
        - api1
        - api2
